name: Bump version and auto-release
on:
  push:
    branches:
      - main
jobs:
  call-run-python-release:
    uses: openclimatefix/.github/.github/workflows/python-release.yml@v1.7.2
    secrets:
      token: ${{ secrets.PYPI_API_TOKEN }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
