name: Python package tests

on:
  push:
  schedule:
    - cron: "0 12 * * 1"
jobs:
  call-run-python-tests:
    uses: openclimatefix/.github/.github/workflows/python-test.yml@main
    with:
      # 0 means don't use pytest-xdist
      pytest_numcpus: "0"
      # pytest-cov looks at this folder
      pytest_cov_dir: "ocf_datapipes"
      # extra things to install
      sudo_apt_install: "libgeos++-dev libproj-dev proj-data proj-bin"
      #      brew_install: "proj geos librttopo"
      os_list: '["ubuntu-latest"]'
